import { extractVideoId } from "./url-utils";

interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

/**
 * Piped API instances — open-source YouTube proxies.
 * These bypass YouTube's datacenter IP blocking.
 * Format: GET /streams/{videoId} → { title, subtitles: [...] }
 */
const PIPED_INSTANCES = [
  "https://api.piped.private.coffee",
  // Add more working instances here as they become available
];

/**
 * Fetch transcript via Piped API.
 * Piped proxies YouTube requests through non-datacenter IPs.
 */
async function fetchTranscriptPiped(
  videoId: string
): Promise<{ segments: TranscriptSegment[]; title: string }> {
  const errors: string[] = [];

  for (const instance of PIPED_INSTANCES) {
    try {
      console.log(`[YouTube] Trying Piped instance: ${instance}`);

      const res = await fetch(`${instance}/streams/${videoId}`, {
        headers: { Accept: "application/json" },
        signal: AbortSignal.timeout(10000),
      });

      if (!res.ok) {
        errors.push(`${instance}: HTTP ${res.status}`);
        continue;
      }

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const data: any = await res.json();

      if (data.error) {
        errors.push(`${instance}: ${data.error}`);
        continue;
      }

      const title = data.title || "YouTube Video";
      const subtitles = data.subtitles;

      if (!subtitles || subtitles.length === 0) {
        errors.push(`${instance}: no subtitles available`);
        continue;
      }

      console.log(
        `[YouTube] Found ${subtitles.length} subtitle track(s): ${subtitles.map((s: { code: string }) => s.code).join(", ")}`
      );

      // Prefer English manual, then English auto, then first available
      const manualEn = subtitles.find(
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (s: any) => s.code === "en" && !s.autoGenerated
      );
      const autoEn = subtitles.find(
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (s: any) => s.code === "en"
      );
      const selected = manualEn || autoEn || subtitles[0];

      console.log(
        `[YouTube] Using subtitle: lang=${selected.code}, auto=${selected.autoGenerated}, name=${selected.name}`
      );

      // Convert the caption URL to request JSON3 format (much easier to parse)
      // The Piped URL comes with fmt=ttml, we replace it with fmt=json3
      const captionUrl = selected.url.replace("fmt=ttml", "fmt=json3");
      console.log(
        `[YouTube] Fetching captions: ${captionUrl.substring(0, 120)}...`
      );

      const captionRes = await fetch(captionUrl, {
        signal: AbortSignal.timeout(8000),
      });

      if (!captionRes.ok) {
        errors.push(`${instance}: caption fetch returned ${captionRes.status}`);
        continue;
      }

      const captionBody = await captionRes.text();
      console.log(
        `[YouTube] Caption response: ${captionBody.length} chars, starts with: ${captionBody.substring(0, 50)}`
      );

      // Try parsing as JSON3 first, then TTML, then VTT
      let segments = parseJson3(captionBody);

      if (segments.length === 0) {
        console.log("[YouTube] JSON3 parse failed, trying TTML...");
        segments = parseTtml(captionBody);
      }

      if (segments.length === 0) {
        console.log("[YouTube] TTML parse failed, trying VTT...");
        segments = parseVtt(captionBody);
      }

      if (segments.length === 0) {
        errors.push(
          `${instance}: could not parse captions (tried JSON3, TTML, VTT)`
        );
        continue;
      }

      console.log(
        `[YouTube] Success via ${instance}: ${segments.length} segments, ~${segments.map((s) => s.text).join(" ").length} chars`
      );
      return { segments, title };
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Unknown error";
      errors.push(`${instance}: ${msg}`);
      console.error(`[YouTube] ${instance} failed: ${msg}`);
    }
  }

  throw new Error(
    `YouTube transcript extraction failed: ${errors.join("; ")}`
  );
}

/**
 * Parse YouTube JSON3 caption format.
 * Format: { events: [{ tStartMs, dDurationMs, segs: [{ utf8 }] }] }
 */
function parseJson3(body: string): TranscriptSegment[] {
  try {
    const data = JSON.parse(body);
    if (!data.events || !Array.isArray(data.events)) return [];

    const segments: TranscriptSegment[] = [];
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    for (const event of data.events) {
      if (!event.segs) continue;
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const text = event.segs.map((s: any) => s.utf8 || "").join("").trim();
      if (text && text !== "\n") {
        segments.push({
          text: decodeEntities(text),
          start: (event.tStartMs || 0) / 1000,
          duration: (event.dDurationMs || 0) / 1000,
        });
      }
    }
    return segments;
  } catch {
    return [];
  }
}

/**
 * Parse TTML (Timed Text Markup Language) captions.
 * Format: <p begin="00:00:07.589" end="00:00:08.049">Text</p>
 */
function parseTtml(ttml: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];

  const pRegex =
    /<p\s+begin="([^"]+)"\s+end="([^"]+)"[^>]*>([\s\S]*?)<\/p>/g;

  let match;
  while ((match = pRegex.exec(ttml)) !== null) {
    const start = parseTimestamp(match[1]);
    const end = parseTimestamp(match[2]);
    const text = decodeEntities(match[3].replace(/<[^>]+>/g, "").trim());
    if (text) {
      segments.push({ text, start, duration: end - start });
    }
  }

  // Fallback: <text start="" dur=""> format
  if (segments.length === 0) {
    const textRegex =
      /<text\s+start="([^"]+)"\s+dur="([^"]+)"[^>]*>([\s\S]*?)<\/text>/g;
    while ((match = textRegex.exec(ttml)) !== null) {
      const start = parseFloat(match[1]);
      const duration = parseFloat(match[2]);
      const text = decodeEntities(match[3].trim());
      if (text) {
        segments.push({ text, start, duration });
      }
    }
  }

  return segments;
}

/**
 * Parse WebVTT captions.
 * Format: "00:00:01.234 --> 00:00:05.678\nText here"
 */
function parseVtt(vtt: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  const cueRegex =
    /(\d{2}:\d{2}:\d{2}\.\d{3})\s+-->\s+(\d{2}:\d{2}:\d{2}\.\d{3})[^\n]*\n([\s\S]*?)(?=\n\n|\n\d{2}:|\s*$)/g;

  let match;
  while ((match = cueRegex.exec(vtt)) !== null) {
    const start = parseTimestamp(match[1]);
    const end = parseTimestamp(match[2]);
    const text = match[3]
      .replace(/<[^>]+>/g, "")
      .replace(/\n/g, " ")
      .trim();
    if (text) {
      segments.push({ text, start, duration: end - start });
    }
  }

  return segments;
}

/**
 * Parse timestamp: "HH:MM:SS.mmm" → seconds
 */
function parseTimestamp(ts: string): number {
  const parts = ts.split(":");
  if (parts.length === 3) {
    const hours = parseInt(parts[0]);
    const minutes = parseInt(parts[1]);
    const seconds = parseFloat(parts[2]);
    return hours * 3600 + minutes * 60 + seconds;
  }
  return parseFloat(ts) || 0;
}

function decodeEntities(text: string): string {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, num) => String.fromCharCode(parseInt(num)))
    .replace(/\n/g, " ");
}

export async function extractYouTube(url: string) {
  const videoId = extractVideoId(url);
  if (!videoId) throw new Error("Invalid YouTube URL");

  console.log(`[YouTube] Extracting video: ${videoId}`);

  const { segments, title } = await fetchTranscriptPiped(videoId);
  const content = segments.map((s) => s.text).join(" ");

  if (!content.trim()) {
    throw new Error("Transcript was empty after extraction.");
  }

  console.log(
    `[YouTube] Final transcript: ${content.length} chars for "${title}"`
  );

  return { title, content, type: "youtube" as const, url };
}
