import { extractVideoId } from "./url-utils";

interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

/**
 * Piped API instances — open-source YouTube proxies.
 * These bypass YouTube's datacenter IP blocking.
 * Format: GET /streams/{videoId} → { title, subtitles: [...] }
 */
const PIPED_INSTANCES = [
  "https://api.piped.private.coffee",
  // Add more working instances here as they become available
];

/**
 * Fetch transcript via Piped API.
 * Piped proxies YouTube requests through non-datacenter IPs.
 */
async function fetchTranscriptPiped(
  videoId: string
): Promise<{ segments: TranscriptSegment[]; title: string }> {
  const errors: string[] = [];

  for (const instance of PIPED_INSTANCES) {
    try {
      console.log(`[YouTube] Trying Piped instance: ${instance}`);

      const res = await fetch(`${instance}/streams/${videoId}`, {
        headers: { Accept: "application/json" },
        signal: AbortSignal.timeout(10000),
      });

      if (!res.ok) {
        errors.push(`${instance}: HTTP ${res.status}`);
        continue;
      }

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const data: any = await res.json();

      if (data.error) {
        errors.push(`${instance}: ${data.error}`);
        continue;
      }

      const title = data.title || "YouTube Video";
      const subtitles = data.subtitles;

      if (!subtitles || subtitles.length === 0) {
        errors.push(`${instance}: no subtitles available`);
        continue;
      }

      console.log(
        `[YouTube] Found ${subtitles.length} subtitle track(s): ${subtitles.map((s: { code: string }) => s.code).join(", ")}`
      );

      // Prefer English manual, then English auto, then first available
      const manualEn = subtitles.find(
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (s: any) => s.code === "en" && !s.autoGenerated
      );
      const autoEn = subtitles.find(
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (s: any) => s.code === "en"
      );
      const selected = manualEn || autoEn || subtitles[0];

      console.log(
        `[YouTube] Using subtitle: lang=${selected.code}, auto=${selected.autoGenerated}, name=${selected.name}`
      );

      // Fetch the TTML caption content
      const captionRes = await fetch(selected.url, {
        signal: AbortSignal.timeout(8000),
      });

      if (!captionRes.ok) {
        errors.push(`${instance}: caption fetch returned ${captionRes.status}`);
        continue;
      }

      const ttml = await captionRes.text();
      console.log(`[YouTube] Caption TTML size: ${ttml.length} chars`);

      const segments = parseTtml(ttml);

      if (segments.length === 0) {
        errors.push(`${instance}: could not parse TTML`);
        continue;
      }

      console.log(
        `[YouTube] Success via ${instance}: ${segments.length} segments`
      );
      return { segments, title };
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Unknown error";
      errors.push(`${instance}: ${msg}`);
      console.error(`[YouTube] ${instance} failed: ${msg}`);
    }
  }

  throw new Error(
    `YouTube transcript extraction failed: ${errors.join("; ")}`
  );
}

/**
 * Parse TTML (Timed Text Markup Language) captions.
 * Format: <p begin="00:00:07.589" end="00:00:08.049" style="s2">Text</p>
 */
function parseTtml(ttml: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];

  // Match <p> elements with begin and end attributes
  const pRegex =
    /<p\s+begin="([^"]+)"\s+end="([^"]+)"[^>]*>([\s\S]*?)<\/p>/g;

  let match;
  while ((match = pRegex.exec(ttml)) !== null) {
    const start = parseTtmlTimestamp(match[1]);
    const end = parseTtmlTimestamp(match[2]);
    // Strip any inner XML/HTML tags (like <span>) and decode entities
    const text = decodeEntities(match[3].replace(/<[^>]+>/g, "").trim());
    if (text) {
      segments.push({ text, start, duration: end - start });
    }
  }

  // Fallback: try XML <text> format (some responses use this)
  if (segments.length === 0) {
    const textRegex =
      /<text\s+start="([^"]+)"\s+dur="([^"]+)"[^>]*>([\s\S]*?)<\/text>/g;
    while ((match = textRegex.exec(ttml)) !== null) {
      const start = parseFloat(match[1]);
      const duration = parseFloat(match[2]);
      const text = decodeEntities(match[3].trim());
      if (text) {
        segments.push({ text, start, duration });
      }
    }
  }

  return segments;
}

/**
 * Parse TTML timestamp format: "HH:MM:SS.mmm" → seconds
 */
function parseTtmlTimestamp(ts: string): number {
  const parts = ts.split(":");
  if (parts.length === 3) {
    const hours = parseInt(parts[0]);
    const minutes = parseInt(parts[1]);
    const seconds = parseFloat(parts[2]);
    return hours * 3600 + minutes * 60 + seconds;
  }
  // Fallback: try parsing as plain seconds
  return parseFloat(ts) || 0;
}

function decodeEntities(text: string): string {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, num) => String.fromCharCode(parseInt(num)))
    .replace(/\n/g, " ");
}

export async function extractYouTube(url: string) {
  const videoId = extractVideoId(url);
  if (!videoId) throw new Error("Invalid YouTube URL");

  console.log(`[YouTube] Extracting video: ${videoId}`);

  const { segments, title } = await fetchTranscriptPiped(videoId);
  const content = segments.map((s) => s.text).join(" ");

  if (!content.trim()) {
    throw new Error("Transcript was empty after extraction.");
  }

  return { title, content, type: "youtube" as const, url };
}
